CREATE DATABASE IF NOT EXISTS TOY_STORE;

DROP TABLE IF EXISTS TOY_STORE.CATEGORY;
CREATE TABLE IF NOT EXISTS TOY_STORE.CATEGORY(
    ID_CATEGORY				INTEGER 		UNSIGNED		NOT NULL		AUTO_INCREMENT,
    NAME_CATEGORY			VARCHAR(155)	NOT NULL,
    IMAGE_NAME_CATEGORY		VARCHAR(255)	NOT NULL,
    
    CONSTRAINT PK_CATEGORY PRIMARY KEY (ID_CATEGORY)
) ENGINE=INNODB;

DROP TABLE IF EXISTS TOY_STORE.PRODUCT;
CREATE TABLE IF NOT EXISTS TOY_STORE.PRODUCT(
	ID_PRODUCT				INTEGER			UNSIGNED		NOT NULL		AUTO_INCREMENT,
    NAME_PRODUCT			VARCHAR(255)	NOT NULL,
	PRICE_PRODUCT			DOUBLE			NOT NULL,
    DESCRIPTION_PRODUCT		TEXT,
    IMAGE_NAME_PRODUCT		VARCHAR(255)	NOT NULL,
    BRAND_PRODUCT			VARCHAR(255)	NOT NULL,
    ID_CATEGORY				INTEGER			UNSIGNED		NOT NULL,

    CONSTRAINT PK_PRODUCT PRIMARY KEY(ID_PRODUCT),
	CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES TOY_STORE.CATEGORY (ID_CATEGORY)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TOY_STORE.USER (
	ID_USER					INTEGER			UNSIGNED		NOT NULL		AUTO_INCREMENT,
    USERNAME_USER			VARCHAR(155)	NOT NULL,
    PASSWORD_USER			VARCHAR(155)	NOT NULL,
    
    CONSTRAINT PK_USER PRIMARY KEY (ID_USER)
) ENGINE=INNODB;

INSERT INTO TOY_STORE.USER (USERNAME_USER, PASSWORD_USER) VALUES ("admin", "1234");

SELECT *
	FROM TOY_STORE.CATEGORY;

SELECT *
	FROM TOY_STORE.PRODUCT;
    
SELECT *
	FROM TOY_STORE.USER
WHERE USERNAME_USER = "admin";
    
SELECT 
	PROD.ID_PRODUCT AS ID,
    PROD.NAME_PRODUCT AS NOME,
    PROD.PRICE_PRODUCT AS PRECO,
    PROD.DESCRIPTION_PRODUCT AS DESCRICAO
FROM TOY_STORE.PRODUCT AS PROD
WHERE PROD.ID_PRODUCT = 1;

SELECT 
	PROD.ID_PRODUCT AS ID,
    PROD.NAME_PRODUCT AS NOME,
    PROD.PRICE_PRODUCT AS PRECO,
    PROD.DESCRIPTION_PRODUCT AS DESCRICAO
FROM TOY_STORE.PRODUCT AS PROD
	INNER JOIN TOY_STORE.CATEGORY AS CAT ON PROD.ID_CATEGORY = CAT.ID_CATEGORY
WHERE PROD.ID_CATEGORY = 1;

SELECT 
	*
FROM TOY_STORE.PRODUCT AS PROD
	INNER JOIN TOY_STORE.CATEGORY AS CAT ON PROD.ID_CATEGORY = CAT.ID_CATEGORY;
